POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jay"
}

###

GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmF5IiwiaWF0IjoxNjU3NjEwNzE5fQ.zmtXbs76kBVznyDY1b_B5iwkxpzBlb-OIIFB1WQF7II